name: session_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none # Change to pub.dev later
repository: https://github.com/f-person/session_dart

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  convert: ^3.1.1
  hashlib: ^1.12.0
  sodium:
    path: /Users/fperson/workspace/forks/libsodium_dart_bindings/packages/sodium

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
